version: "{build}"

os: unstable

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@5.8.0
  - npm ci
  - cd windows && npm ci && cd..

before_build:
  - npm run lint windows

build_script:
  - cd windows
  - npm run build
  - npm run choco

test_script:
  - cd ..
  - npm run test:windows

cache:
  - node_modules
  - windows\node_modules
  - '%APPDATA%\npm-cache'

artifacts:
  - path: windows\build\installers\*.exe
    name: HeadsetApp
  - path: windows\build\*.nupkg
    name: HeadsetChoco

deploy:
  - provider: GitHub
    artifact: HeadsetApp
    auth_token: $(GITHUB_TOKEN)
    draft: true
    description: ''
    on:
      appveyor_repo_tag: true
